---
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: --config /config.yaml
    ports:
      - 4317:4317
      - 8006:8006
    volumes:
      - ./collector.yaml:/config.yaml:ro
      - ./logs:/otel-logs:rwz

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 16686:16686
